package status

import "time"

// Description: Access search concurrency metrics for a standalone Splunk Enterprise instance.
// Rest End Point: services/server/status/limits/search-concurrency

type AutoGenerated struct {
	Links struct {
	} `json:"links"`
	Origin    string    `json:"origin"`
	Updated   time.Time `json:"updated"`
	Generator struct {
		Build   string `json:"build"`
		Version string `json:"version"`
	} `json:"generator"`
	Entry []struct {
		Name    string    `json:"name"`
		ID      string    `json:"id"`
		Updated time.Time `json:"updated"`
		Links   struct {
			Alternate string `json:"alternate"`
			List      string `json:"list"`
		} `json:"links"`
		Author string `json:"author"`
		ACL    struct {
			App        string `json:"app"`
			CanList    bool   `json:"can_list"`
			CanWrite   bool   `json:"can_write"`
			Modifiable bool   `json:"modifiable"`
			Owner      string `json:"owner"`
			Perms      struct {
				Read  []string      `json:"read"`
				Write []interface{} `json:"write"`
			} `json:"perms"`
			Removable bool   `json:"removable"`
			Sharing   string `json:"sharing"`
		} `json:"acl"`
		Content struct {
			EaiACL                   interface{} `json:"eai:acl"`
			MaxAutoSummarySearches   int         `json:"max_auto_summary_searches"`
			MaxHistScheduledSearches int         `json:"max_hist_scheduled_searches"`
			MaxHistSearches          int         `json:"max_hist_searches"`
			MaxRtScheduledSearches   int         `json:"max_rt_scheduled_searches"`
			MaxRtSearches            int         `json:"max_rt_searches"`
		} `json:"content"`
	} `json:"entry"`
	Paging struct {
		Total   int `json:"total"`
		PerPage int `json:"perPage"`
		Offset  int `json:"offset"`
	} `json:"paging"`
	Messages []interface{} `json:"messages"`
}
