//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfig) DeepCopyInto(out *BackupConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfig.
func (in *BackupConfig) DeepCopy() *BackupConfig {
	if in == nil {
		return nil
	}
	out := new(BackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(VolumeSnapshotBackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStoreBackupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapFrom) DeepCopyInto(out *BootstrapFrom) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(VolumeSnapshotSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorageSource)
		**out = **in
	}
	if in.RecoveryTarget != nil {
		in, out := &in.RecoveryTarget, &out.RecoveryTarget
		*out = new(RecoveryTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapFrom.
func (in *BootstrapFrom) DeepCopy() *BootstrapFrom {
	if in == nil {
		return nil
	}
	out := new(BootstrapFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBackupConfig) DeepCopyInto(out *CNPGBackupConfig) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(CNPGVolumeSnapshotConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BarmanObjectStore != nil {
		in, out := &in.BarmanObjectStore, &out.BarmanObjectStore
		*out = new(CNPGBarmanObjectStoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBackupConfig.
func (in *CNPGBackupConfig) DeepCopy() *CNPGBackupConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBarmanObjectStoreConfig) DeepCopyInto(out *CNPGBarmanObjectStoreConfig) {
	*out = *in
	if in.EndpointURL != nil {
		in, out := &in.EndpointURL, &out.EndpointURL
		*out = new(string)
		**out = **in
	}
	in.S3Credentials.DeepCopyInto(&out.S3Credentials)
	if in.WAL != nil {
		in, out := &in.WAL, &out.WAL
		*out = new(CNPGBarmanWALConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBarmanObjectStoreConfig.
func (in *CNPGBarmanObjectStoreConfig) DeepCopy() *CNPGBarmanObjectStoreConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGBarmanObjectStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBarmanS3Credentials) DeepCopyInto(out *CNPGBarmanS3Credentials) {
	*out = *in
	in.AccessKeyId.DeepCopyInto(&out.AccessKeyId)
	in.SecretAccessKey.DeepCopyInto(&out.SecretAccessKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBarmanS3Credentials.
func (in *CNPGBarmanS3Credentials) DeepCopy() *CNPGBarmanS3Credentials {
	if in == nil {
		return nil
	}
	out := new(CNPGBarmanS3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBarmanWALConfig) DeepCopyInto(out *CNPGBarmanWALConfig) {
	*out = *in
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(string)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBarmanWALConfig.
func (in *CNPGBarmanWALConfig) DeepCopy() *CNPGBarmanWALConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGBarmanWALConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGConfig) DeepCopyInto(out *CNPGConfig) {
	*out = *in
	if in.PrimaryUpdateMethod != nil {
		in, out := &in.PrimaryUpdateMethod, &out.PrimaryUpdateMethod
		*out = new(string)
		**out = **in
	}
	if in.ConnectionPooler != nil {
		in, out := &in.ConnectionPooler, &out.ConnectionPooler
		*out = new(ConnectionPoolerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(CNPGBackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGConfig.
func (in *CNPGConfig) DeepCopy() *CNPGConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGVolumeSnapshotConfig) DeepCopyInto(out *CNPGVolumeSnapshotConfig) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.WalClassName != nil {
		in, out := &in.WalClassName, &out.WalClassName
		*out = new(string)
		**out = **in
	}
	if in.SnapshotOwnerReference != nil {
		in, out := &in.SnapshotOwnerReference, &out.SnapshotOwnerReference
		*out = new(string)
		**out = **in
	}
	if in.Online != nil {
		in, out := &in.Online, &out.Online
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGVolumeSnapshotConfig.
func (in *CNPGVolumeSnapshotConfig) DeepCopy() *CNPGVolumeSnapshotConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGVolumeSnapshotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolerConfig) DeepCopyInto(out *ConnectionPoolerConfig) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(ConnectionPoolerMode)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolerConfig.
func (in *ConnectionPoolerConfig) DeepCopy() *ConnectionPoolerConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolerEnableConfig) DeepCopyInto(out *ConnectionPoolerEnableConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ReadWrite != nil {
		in, out := &in.ReadWrite, &out.ReadWrite
		*out = new(bool)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolerEnableConfig.
func (in *ConnectionPoolerEnableConfig) DeepCopy() *ConnectionPoolerEnableConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolerEnableConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolerStatus) DeepCopyInto(out *ConnectionPoolerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolerStatus.
func (in *ConnectionPoolerStatus) DeepCopy() *ConnectionPoolerStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomMetricsStatus) DeepCopyInto(out *CustomMetricsStatus) {
	*out = *in
	if in.DatabaseContributions != nil {
		in, out := &in.DatabaseContributions, &out.DatabaseContributions
		*out = make([]DatabaseCustomMetricsStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomMetricsStatus.
func (in *CustomMetricsStatus) DeepCopy() *CustomMetricsStatus {
	if in == nil {
		return nil
	}
	out := new(CustomMetricsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCustomMetricsContribution) DeepCopyInto(out *DatabaseCustomMetricsContribution) {
	*out = *in
	if in.CustomQueriesConfigMap != nil {
		in, out := &in.CustomQueriesConfigMap, &out.CustomQueriesConfigMap
		*out = make([]v1.ConfigMapKeySelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCustomMetricsContribution.
func (in *DatabaseCustomMetricsContribution) DeepCopy() *DatabaseCustomMetricsContribution {
	if in == nil {
		return nil
	}
	out := new(DatabaseCustomMetricsContribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseCustomMetricsStatus) DeepCopyInto(out *DatabaseCustomMetricsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseCustomMetricsStatus.
func (in *DatabaseCustomMetricsStatus) DeepCopy() *DatabaseCustomMetricsStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseCustomMetricsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDefinition) DeepCopyInto(out *DatabaseDefinition) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PasswordConfig != nil {
		in, out := &in.PasswordConfig, &out.PasswordConfig
		*out = new(PasswordConfig)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(DatabaseMonitoring)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDefinition.
func (in *DatabaseDefinition) DeepCopy() *DatabaseDefinition {
	if in == nil {
		return nil
	}
	out := new(DatabaseDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInfo) DeepCopyInto(out *DatabaseInfo) {
	*out = *in
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.AdminUserSecretRef != nil {
		in, out := &in.AdminUserSecretRef, &out.AdminUserSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RWUserSecretRef != nil {
		in, out := &in.RWUserSecretRef, &out.RWUserSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]DatabaseRoleInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInfo.
func (in *DatabaseInfo) DeepCopy() *DatabaseInfo {
	if in == nil {
		return nil
	}
	out := new(DatabaseInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseMonitoring) DeepCopyInto(out *DatabaseMonitoring) {
	*out = *in
	if in.CustomQueriesConfigMap != nil {
		in, out := &in.CustomQueriesConfigMap, &out.CustomQueriesConfigMap
		*out = make([]v1.ConfigMapKeySelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseMonitoring.
func (in *DatabaseMonitoring) DeepCopy() *DatabaseMonitoring {
	if in == nil {
		return nil
	}
	out := new(DatabaseMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleInfo) DeepCopyInto(out *DatabaseRoleInfo) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleInfo.
func (in *DatabaseRoleInfo) DeepCopy() *DatabaseRoleInfo {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRolesStatus) DeepCopyInto(out *ManagedRolesStatus) {
	*out = *in
	if in.Reconciled != nil {
		in, out := &in.Reconciled, &out.Reconciled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RoleOwners != nil {
		in, out := &in.RoleOwners, &out.RoleOwners
		*out = make(map[string]RoleOwnerReference, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]RoleConflict, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRolesStatus.
func (in *ManagedRolesStatus) DeepCopy() *ManagedRolesStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedRolesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsClassConfig) DeepCopyInto(out *MetricsClassConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsClassConfig.
func (in *MetricsClassConfig) DeepCopy() *MetricsClassConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSource) DeepCopyInto(out *ObjectStorageSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSource.
func (in *ObjectStorageSource) DeepCopy() *ObjectStorageSource {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreBackupStatus) DeepCopyInto(out *ObjectStoreBackupStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreBackupStatus.
func (in *ObjectStoreBackupStatus) DeepCopy() *ObjectStoreBackupStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordConfig) DeepCopyInto(out *PasswordConfig) {
	*out = *in
	out.ExternalAdminSecretRef = in.ExternalAdminSecretRef
	out.ExternalRWSecretRef = in.ExternalRWSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordConfig.
func (in *PasswordConfig) DeepCopy() *PasswordConfig {
	if in == nil {
		return nil
	}
	out := new(PasswordConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresCluster) DeepCopyInto(out *PostgresCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresCluster.
func (in *PostgresCluster) DeepCopy() *PostgresCluster {
	if in == nil {
		return nil
	}
	out := new(PostgresCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClass) DeepCopyInto(out *PostgresClusterClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClass.
func (in *PostgresClusterClass) DeepCopy() *PostgresClusterClass {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassConfig) DeepCopyInto(out *PostgresClusterClassConfig) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.PostgresVersion != nil {
		in, out := &in.PostgresVersion, &out.PostgresVersion
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQLConfig != nil {
		in, out := &in.PostgreSQLConfig, &out.PostgreSQLConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PgHBA != nil {
		in, out := &in.PgHBA, &out.PgHBA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionPooler != nil {
		in, out := &in.ConnectionPooler, &out.ConnectionPooler
		*out = new(ConnectionPoolerEnableConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(PostgresMonitoringClassConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassConfig.
func (in *PostgresClusterClassConfig) DeepCopy() *PostgresClusterClassConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassList) DeepCopyInto(out *PostgresClusterClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresClusterClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassList.
func (in *PostgresClusterClassList) DeepCopy() *PostgresClusterClassList {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassSpec) DeepCopyInto(out *PostgresClusterClassSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(PostgresClusterClassConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CNPG != nil {
		in, out := &in.CNPG, &out.CNPG
		*out = new(CNPGConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassSpec.
func (in *PostgresClusterClassSpec) DeepCopy() *PostgresClusterClassSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassStatus) DeepCopyInto(out *PostgresClusterClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassStatus.
func (in *PostgresClusterClassStatus) DeepCopy() *PostgresClusterClassStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterList) DeepCopyInto(out *PostgresClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterList.
func (in *PostgresClusterList) DeepCopy() *PostgresClusterList {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterMonitoring) DeepCopyInto(out *PostgresClusterMonitoring) {
	*out = *in
	if in.PostgreSQLMetrics != nil {
		in, out := &in.PostgreSQLMetrics, &out.PostgreSQLMetrics
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionPoolerMetrics != nil {
		in, out := &in.ConnectionPoolerMetrics, &out.ConnectionPoolerMetrics
		*out = new(bool)
		**out = **in
	}
	if in.CustomQueriesConfigMap != nil {
		in, out := &in.CustomQueriesConfigMap, &out.CustomQueriesConfigMap
		*out = make([]v1.ConfigMapKeySelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterMonitoring.
func (in *PostgresClusterMonitoring) DeepCopy() *PostgresClusterMonitoring {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterResources) DeepCopyInto(out *PostgresClusterResources) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.SuperUserSecretRef != nil {
		in, out := &in.SuperUserSecretRef, &out.SuperUserSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterResources.
func (in *PostgresClusterResources) DeepCopy() *PostgresClusterResources {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterSpec) DeepCopyInto(out *PostgresClusterSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.PostgresVersion != nil {
		in, out := &in.PostgresVersion, &out.PostgresVersion
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQLConfig != nil {
		in, out := &in.PostgreSQLConfig, &out.PostgreSQLConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PgHBA != nil {
		in, out := &in.PgHBA, &out.PgHBA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionPooler != nil {
		in, out := &in.ConnectionPooler, &out.ConnectionPooler
		*out = new(ConnectionPoolerEnableConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterDeletionPolicy != nil {
		in, out := &in.ClusterDeletionPolicy, &out.ClusterDeletionPolicy
		*out = new(string)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(PostgresClusterMonitoring)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapFrom != nil {
		in, out := &in.BootstrapFrom, &out.BootstrapFrom
		*out = new(BootstrapFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordConfig != nil {
		in, out := &in.PasswordConfig, &out.PasswordConfig
		*out = new(SuperuserPasswordConfig)
		**out = **in
	}
	if in.PostgresMajorUpgradeConfig != nil {
		in, out := &in.PostgresMajorUpgradeConfig, &out.PostgresMajorUpgradeConfig
		*out = new(PostgresMajorUpgradeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterSpec.
func (in *PostgresClusterSpec) DeepCopy() *PostgresClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterStatus) DeepCopyInto(out *PostgresClusterStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.ProvisionerRef != nil {
		in, out := &in.ProvisionerRef, &out.ProvisionerRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.ConnectionPoolerStatus != nil {
		in, out := &in.ConnectionPoolerStatus, &out.ConnectionPoolerStatus
		*out = new(ConnectionPoolerStatus)
		**out = **in
	}
	if in.ManagedRolesStatus != nil {
		in, out := &in.ManagedRolesStatus, &out.ManagedRolesStatus
		*out = new(ManagedRolesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomMetricsStatus != nil {
		in, out := &in.CustomMetricsStatus, &out.CustomMetricsStatus
		*out = new(CustomMetricsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(PostgresClusterResources)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.ReadyInstances != nil {
		in, out := &in.ReadyInstances, &out.ReadyInstances
		*out = new(int32)
		**out = **in
	}
	if in.CurrentPrimary != nil {
		in, out := &in.CurrentPrimary, &out.CurrentPrimary
		*out = new(string)
		**out = **in
	}
	if in.PostgresMajorUpgradeStatus != nil {
		in, out := &in.PostgresMajorUpgradeStatus, &out.PostgresMajorUpgradeStatus
		*out = make([]PostgresMajorUpgradeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterStatus.
func (in *PostgresClusterStatus) DeepCopy() *PostgresClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabase) DeepCopyInto(out *PostgresDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabase.
func (in *PostgresDatabase) DeepCopy() *PostgresDatabase {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseCustomMetricsPublication) DeepCopyInto(out *PostgresDatabaseCustomMetricsPublication) {
	*out = *in
	if in.Contributions != nil {
		in, out := &in.Contributions, &out.Contributions
		*out = make([]DatabaseCustomMetricsContribution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseCustomMetricsPublication.
func (in *PostgresDatabaseCustomMetricsPublication) DeepCopy() *PostgresDatabaseCustomMetricsPublication {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseCustomMetricsPublication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseList) DeepCopyInto(out *PostgresDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseList.
func (in *PostgresDatabaseList) DeepCopy() *PostgresDatabaseList {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseSpec) DeepCopyInto(out *PostgresDatabaseSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseSpec.
func (in *PostgresDatabaseSpec) DeepCopy() *PostgresDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseStatus) DeepCopyInto(out *PostgresDatabaseStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomMetricsPublication != nil {
		in, out := &in.CustomMetricsPublication, &out.CustomMetricsPublication
		*out = new(PostgresDatabaseCustomMetricsPublication)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseStatus.
func (in *PostgresDatabaseStatus) DeepCopy() *PostgresDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMajorUpgradeConfig) DeepCopyInto(out *PostgresMajorUpgradeConfig) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMajorUpgradeConfig.
func (in *PostgresMajorUpgradeConfig) DeepCopy() *PostgresMajorUpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresMajorUpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMajorUpgradeStatus) DeepCopyInto(out *PostgresMajorUpgradeStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.SourcePgVersion != nil {
		in, out := &in.SourcePgVersion, &out.SourcePgVersion
		*out = new(string)
		**out = **in
	}
	if in.TargetPgVersion != nil {
		in, out := &in.TargetPgVersion, &out.TargetPgVersion
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupNames != nil {
		in, out := &in.BackupNames, &out.BackupNames
		*out = new(UpgradeBackupNames)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMajorUpgradeStatus.
func (in *PostgresMajorUpgradeStatus) DeepCopy() *PostgresMajorUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresMajorUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMonitoringClassConfig) DeepCopyInto(out *PostgresMonitoringClassConfig) {
	*out = *in
	if in.PostgreSQLMetrics != nil {
		in, out := &in.PostgreSQLMetrics, &out.PostgreSQLMetrics
		*out = new(MetricsClassConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionPoolerMetrics != nil {
		in, out := &in.ConnectionPoolerMetrics, &out.ConnectionPoolerMetrics
		*out = new(MetricsClassConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMonitoringClassConfig.
func (in *PostgresMonitoringClassConfig) DeepCopy() *PostgresMonitoringClassConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresMonitoringClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTarget) DeepCopyInto(out *RecoveryTarget) {
	*out = *in
	if in.Exclusive != nil {
		in, out := &in.Exclusive, &out.Exclusive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTarget.
func (in *RecoveryTarget) DeepCopy() *RecoveryTarget {
	if in == nil {
		return nil
	}
	out := new(RecoveryTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTargetStatus) DeepCopyInto(out *RecoveryTargetStatus) {
	*out = *in
	if in.Exclusive != nil {
		in, out := &in.Exclusive, &out.Exclusive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTargetStatus.
func (in *RecoveryTargetStatus) DeepCopy() *RecoveryTargetStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreCredentialSweepStatus) DeepCopyInto(out *RestoreCredentialSweepStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreCredentialSweepStatus.
func (in *RestoreCredentialSweepStatus) DeepCopy() *RestoreCredentialSweepStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreCredentialSweepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSourceStatus) DeepCopyInto(out *RestoreSourceStatus) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(string)
		**out = **in
	}
	if in.RequestedRecoveryTarget != nil {
		in, out := &in.RequestedRecoveryTarget, &out.RequestedRecoveryTarget
		*out = new(RecoveryTargetStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSourceStatus.
func (in *RestoreSourceStatus) DeepCopy() *RestoreSourceStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.CredentialSweep = in.CredentialSweep
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatus.
func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleConflict) DeepCopyInto(out *RoleConflict) {
	*out = *in
	if in.ClaimedBy != nil {
		in, out := &in.ClaimedBy, &out.ClaimedBy
		*out = new(RoleOwnerReference)
		**out = **in
	}
	out.AttemptedBy = in.AttemptedBy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleConflict.
func (in *RoleConflict) DeepCopy() *RoleConflict {
	if in == nil {
		return nil
	}
	out := new(RoleConflict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleOwnerReference) DeepCopyInto(out *RoleOwnerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleOwnerReference.
func (in *RoleOwnerReference) DeepCopy() *RoleOwnerReference {
	if in == nil {
		return nil
	}
	out := new(RoleOwnerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperuserPasswordConfig) DeepCopyInto(out *SuperuserPasswordConfig) {
	*out = *in
	out.SuperuserExternalSecretRef = in.SuperuserExternalSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperuserPasswordConfig.
func (in *SuperuserPasswordConfig) DeepCopy() *SuperuserPasswordConfig {
	if in == nil {
		return nil
	}
	out := new(SuperuserPasswordConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeBackupNames) DeepCopyInto(out *UpgradeBackupNames) {
	*out = *in
	if in.PreUpgrade != nil {
		in, out := &in.PreUpgrade, &out.PreUpgrade
		*out = new(string)
		**out = **in
	}
	if in.PostUpgrade != nil {
		in, out := &in.PostUpgrade, &out.PostUpgrade
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeBackupNames.
func (in *UpgradeBackupNames) DeepCopy() *UpgradeBackupNames {
	if in == nil {
		return nil
	}
	out := new(UpgradeBackupNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotBackupStatus) DeepCopyInto(out *VolumeSnapshotBackupStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotBackupStatus.
func (in *VolumeSnapshotBackupStatus) DeepCopy() *VolumeSnapshotBackupStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotSource) DeepCopyInto(out *VolumeSnapshotSource) {
	*out = *in
	if in.WalStorage != nil {
		in, out := &in.WalStorage, &out.WalStorage
		*out = new(string)
		**out = **in
	}
	if in.WalArchive != nil {
		in, out := &in.WalArchive, &out.WalArchive
		*out = new(ObjectStorageSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotSource.
func (in *VolumeSnapshotSource) DeepCopy() *VolumeSnapshotSource {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotSource)
	in.DeepCopyInto(out)
	return out
}
