sonar.projectKey=sok.splunk-operator
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.exclusions=**/*_test.go,bin/**,build/**,bundle/**,coverage/**,deploy/olm-certified/**,.cache/**,.helm-data/**,.sonar/**,vendor/**
sonar.coverage.exclusions=**/*_test.go,**/zz_generated*.go,api/**/zz_generated.deepcopy.go,cmd/**,config/**,test/**,tools/**,bundle/**
sonar.go.coverage.reportPaths=coverage.out
