{{- if .Values.objectStorage.enabled }}
{{- if .Values.objectStorage.enabled }}
apiVersion: enterprise.splunk.com/v4
kind: ObjectStorage
metadata:
  name: {{ .Values.objectStorage.name }}
  namespace: {{ default .Release.Namespace .Values.objectStorage.namespaceOverride }}
  {{- with .Values.objectStorage.additionalLabels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.objectStorage.additionalAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ .Values.objectStorage.provider | quote }}
  {{- with .Values.objectStorage.s3 }}
  s3:
    {{- if .endpoint }}
    endpoint: {{ .endpoint | quote }}
    {{- end }}
    {{- if .path }}
    path: {{ .path | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}