{{- if .Values.queue }}
{{- if .Values.queue.enabled }}
apiVersion: enterprise.splunk.com/v4
kind: Queue
metadata:
  name: {{ .Values.queue.name }}
  namespace: {{ default .Release.Namespace .Values.queue.namespaceOverride }}
  {{- with .Values.queue.additionalLabels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.queue.additionalAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ .Values.queue.provider | quote }}
  {{- with .Values.queue.sqs }}
  sqs:
    {{- if .endpoint }}
    endpoint: {{ .endpoint | quote }}
    {{- end }}
    {{- if .dlq }}
    dlq: {{ .dlq | quote }}
    {{- end }}
    {{- if .name }}
    name: {{ .name | quote }}
    {{- end }}
    {{- if .region }}
    region: {{ .region | quote }}
    {{- end }}
    {{- if .volumes }}
    volumes:
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}