{{- if .Values.largeMessageStore }}
{{- if .Values.largeMessageStore.enabled }}
apiVersion: enterprise.splunk.com/v4
kind: LargeMessageStore
metadata:
  name: {{ .Values.largeMessageStore.name }}
  namespace: {{ default .Release.Namespace .Values.largeMessageStore.namespaceOverride }}
  {{- with .Values.largeMessageStore.additionalLabels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.largeMessageStore.additionalAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ .Values.largeMessageStore.provider | quote }}
  {{- with .Values.largeMessageStore.s3 }}
  s3:
    {{- if .endpoint }}
    endpoint: {{ .endpoint | quote }}
    {{- end }}
    {{- if .path }}
    path: {{ .path | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}