apiVersion: v1
kind: Service
metadata:
  name: {{ include "noah.minioName" . }}
  labels:
    {{- include "noah.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  ports:
    - name: s3
      port: {{ .Values.minio.service.port }}
      targetPort: s3
  selector:
    {{- include "noah.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
