apiVersion: v1
kind: Service
metadata:
  name: {{ include "noah.fullname" . }}
  labels:
    {{- include "noah.labels" . | nindent 4 }}
    app.kubernetes.io/component: noah
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
  selector:
    {{- include "noah.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: noah
