apiVersion: v1
kind: Service
metadata:
  name: {{ include "noah.postgresqlName" . }}
  labels:
    {{- include "noah.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
  selector:
    {{- include "noah.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
