apiVersion: v1
kind: Service
metadata:
  name: {{ include "noah.redisName" . }}
  labels:
    {{- include "noah.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "noah.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
