# This rule is not used by the project splunk-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over enterprise.splunk.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: databaseclass-admin-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - databaseclasses
  verbs:
  - '*'
- apiGroups:
  - enterprise.splunk.com
  resources:
  - databaseclasses/status
  verbs:
  - get
