url: "https://sok.splunkdev.page"
baseurl: "/splunk-operator"
remote_theme: null
theme: just-the-docs
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
exclude:
  - splunk_private/vendor
aux_links:
  "View on GitLab":
    - https://cd.splunkdev.com/sok/splunk-operator
