format-and-vet:
  extends: .go-verify-job
  script:
    - make fmt
    - make vet
    - git diff --exit-code

unit-tests:
  extends: .go-test-job
  needs:
    - format-and-vet
  variables:
    GOFLAGS: ""
  script:
    - make setup/ginkgo
    - make test
    - go tool cover -func=coverage.out | tee coverage-summary.txt
  artifacts:
    when: always
    paths:
      - coverage.out
      - coverage-summary.txt
      - unit_test.xml
    reports:
      junit: unit_test.xml
  coverage: '/^total:\s+\(statements\)\s+(\d+\.\d+)%$/'

kubectl-splunk-tests:
  extends:
    - .go-test-job
    - .kubectl-splunk-python-job
  script:
    - cd tools/kubectl-splunk
    - coverage run -m unittest discover -s tests
    - coverage report | tee "$CI_PROJECT_DIR/kubectl-splunk-coverage-summary.txt"
    - coverage xml -o "$CI_PROJECT_DIR/kubectl-splunk-coverage.xml"
  artifacts:
    when: always
    paths:
      - kubectl-splunk-coverage-summary.txt
      - kubectl-splunk-coverage.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: kubectl-splunk-coverage.xml
