apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_license_master_s1
  tags: [operator, licensemaster, smoke, s1]
topology:
  kind: s1
steps:
  - name: deploy
    action: topology.deploy
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_master
    action: splunk.license_master.deploy
  - name: wait_license_master
    action: splunk.license_master.wait_ready
  - name: patch_standalone_license
    action: k8s.resource.patch
    with:
      kind: Standalone
      name: ${standalone_name}
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: wait_standalone
    action: assert.splunk.phase
    with:
      kind: Standalone
      name: ${standalone_name}
      phase: Ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: ${base_name}
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
  - name: probe_configmap
    action: assert.k8s.configmap.exists
    with:
      name: splunk-${namespace}-probe-configmap
  - name: probe_scripts
    action: assert.k8s.pod.files.present
    with:
      pods:
        - splunk-${standalone_name}-standalone-0
        - splunk-${license_master_name}-license-master-0
        - splunk-${monitoring_console_name}-monitoring-console-0
      files:
        - livenessProbe.sh
        - readinessProbe.sh
      path: /mnt/probes
  - name: lm_configured
    action: splunk.license_manager.verify_configured
    with:
      expected_contains: license-master-service:8089
      pods:
        - splunk-${standalone_name}-standalone-0
        - splunk-${monitoring_console_name}-monitoring-console-0
---
apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_license_master_c3
  tags: [operator, licensemaster, integration, c3]
topology:
  kind: c3
  params:
    cluster_manager_kind: master
steps:
  - name: deploy
    action: topology.deploy
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_master
    action: splunk.license_master.deploy
  - name: patch_cluster_master_license
    action: k8s.resource.patch
    with:
      apiVersion: enterprise.splunk.com/v3
      kind: ClusterMaster
      name: ${cluster_manager_name}
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: patch_indexer_cluster_license
    action: k8s.resource.patch
    with:
      kind: IndexerCluster
      name: ${indexer_cluster_name}
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: patch_search_head_license
    action: k8s.resource.patch
    with:
      kind: SearchHeadCluster
      name: ${search_head_cluster_name}
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: wait_license_master
    action: splunk.license_master.wait_ready
  - name: wait_topology
    action: topology.wait_ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: ${base_name}
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
  - name: rf_sf
    action: assert.cluster.rf_sf
  - name: lm_configured
    action: splunk.license_manager.verify_configured
    with:
      expected_contains: license-master-service:8089
      pods:
        - splunk-${base_name}-idxc-indexer-0
        - splunk-${base_name}-idxc-indexer-1
        - splunk-${base_name}-idxc-indexer-2
        - splunk-${base_name}-shc-search-head-0
        - splunk-${base_name}-shc-search-head-1
        - splunk-${base_name}-shc-search-head-2
        - splunk-${monitoring_console_name}-monitoring-console-0
---
apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_license_master_m4
  tags: [operator, licensemaster, integration, m4]
topology:
  kind: m4
  params:
    cluster_manager_kind: master
    indexer_replicas: "1"
    site_count: "3"
steps:
  - name: deploy
    action: topology.deploy
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_master
    action: splunk.license_master.deploy
  - name: patch_cluster_master_license
    action: k8s.resource.patch
    with:
      apiVersion: enterprise.splunk.com/v3
      kind: ClusterMaster
      name: ${cluster_manager_name}
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: patch_indexer_site1_license
    action: k8s.resource.patch
    with:
      kind: IndexerCluster
      name: ${base_name}-site1
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: patch_indexer_site2_license
    action: k8s.resource.patch
    with:
      kind: IndexerCluster
      name: ${base_name}-site2
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: patch_indexer_site3_license
    action: k8s.resource.patch
    with:
      kind: IndexerCluster
      name: ${base_name}-site3
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: patch_search_head_license
    action: k8s.resource.patch
    with:
      kind: SearchHeadCluster
      name: ${search_head_cluster_name}
      spec:
        licenseMasterRef:
          name: ${license_master_name}
  - name: wait_license_master
    action: splunk.license_master.wait_ready
  - name: wait_topology
    action: topology.wait_ready
  - name: multisite_sites
    action: assert.cluster.multisite_sites
    with:
      site_count: 3
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: ${base_name}
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
  - name: rf_sf
    action: assert.cluster.rf_sf
  - name: lm_configured
    action: splunk.license_manager.verify_configured
    with:
      expected_contains: license-master-service:8089
      pods:
        - splunk-${base_name}-site1-indexer-0
        - splunk-${base_name}-site2-indexer-0
        - splunk-${base_name}-site3-indexer-0
        - splunk-${base_name}-shc-search-head-0
        - splunk-${base_name}-shc-search-head-1
        - splunk-${base_name}-shc-search-head-2
        - splunk-${monitoring_console_name}-monitoring-console-0
