apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_secret_s1_update
  description: Secret update on standalone with LM and MC (source test/secret/manager_secret_s1_test.go)
  component: secret
  tags: [operator, secret, s1, integration]
variants:
  - name: operator_secret_manager_s1_update
    tags: [managersecret]
  - name: operator_secret_master_s1_update
    tags: [mastersecret]
requires: [license]
steps:
  - name: deploy
    action: topology.deploy
    with:
      kind: s1
      license_manager_ref: lm
      monitoring_console_ref: mc
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_manager
    action: splunk.license_manager.deploy
    with:
      name: lm
  - name: wait_license_manager
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_ready
    action: topology.wait_ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: mc
      license_manager_ref: lm
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: capture_mc_resource_version
    action: k8s.resource.version.capture
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: capture_secret
    action: secret.capture
  - name: generate_secret
    action: secret.generate
  - name: update_secret
    action: secret.update
  - name: assert_standalone_updating
    action: assert.splunk.phase
    with:
      kind: Standalone
      name: ${standalone_name}
      apiVersion: enterprise.splunk.com/v4
      phase: Updating
  - name: wait_license_manager_again
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_again
    action: topology.wait_ready
  - name: wait_mc_resource_version_change
    action: k8s.resource.version.wait_change
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: wait_monitoring_console_again
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: list_versioned_secrets
    action: secret.versioned.list
    with:
      version: 2
  - name: verify_secret_objects
    action: secret.verify.objects
    with:
      match: true
  - name: verify_secret_pods
    action: secret.verify.pods
    with:
      match: true
  - name: verify_server_conf
    action: secret.verify.server_conf
    with:
      match: true
  - name: verify_inputs_conf
    action: secret.verify.inputs_conf
    with:
      match: true
  - name: verify_api
    action: secret.verify.api
    with:
      match: true
---
apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_secret_s1_delete
  description: Secret delete recreates namespace secret on standalone with LM and MC (source test/secret/manager_secret_s1_test.go)
  component: secret
  tags: [operator, secret, s1, integration]
variants:
  - name: operator_secret_manager_s1_delete
    tags: [managersecret]
  - name: operator_secret_master_s1_delete
    tags: [mastersecret]
requires: [license]
steps:
  - name: deploy
    action: topology.deploy
    with:
      kind: s1
      license_manager_ref: lm
      monitoring_console_ref: mc
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_manager
    action: splunk.license_manager.deploy
    with:
      name: lm
  - name: wait_license_manager
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_ready
    action: topology.wait_ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: mc
      license_manager_ref: lm
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: capture_mc_resource_version
    action: k8s.resource.version.capture
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: capture_secret
    action: secret.capture
    with:
      var: old_secret_data_path
  - name: delete_secret
    action: secret.delete
  - name: assert_standalone_updating
    action: assert.splunk.phase
    with:
      kind: Standalone
      name: ${standalone_name}
      apiVersion: enterprise.splunk.com/v4
      phase: Updating
  - name: wait_license_manager_again
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_again
    action: topology.wait_ready
  - name: wait_mc_resource_version_change
    action: k8s.resource.version.wait_change
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: wait_monitoring_console_again
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: list_versioned_secrets
    action: secret.versioned.list
    with:
      version: 2
  - name: verify_secret_objects
    action: secret.verify.objects
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_secret_pods
    action: secret.verify.pods
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_server_conf
    action: secret.verify.server_conf
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_inputs_conf
    action: secret.verify.inputs_conf
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_api
    action: secret.verify.api
    with:
      data_path: ${old_secret_data_path}
      match: false
---
apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_secret_s1_empty_data
  description: Secret empty data repopulates on standalone with MC (source test/secret/manager_secret_s1_test.go)
  component: secret
  tags: [operator, secret, s1, smoke]
variants:
  - name: operator_secret_manager_s1_empty_data
    tags: [managersecret]
  - name: operator_secret_master_s1_empty_data
    tags: [mastersecret]
steps:
  - name: deploy
    action: topology.deploy
    with:
      kind: s1
      monitoring_console_ref: mc
  - name: wait_topology_ready
    action: topology.wait_ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: mc
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: capture_mc_resource_version
    action: k8s.resource.version.capture
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: capture_secret
    action: secret.capture
    with:
      var: old_secret_data_path
  - name: generate_empty_secret
    action: secret.generate
    with:
      empty: true
  - name: update_secret
    action: secret.update
  - name: assert_standalone_updating
    action: assert.splunk.phase
    with:
      kind: Standalone
      name: ${standalone_name}
      apiVersion: enterprise.splunk.com/v4
      phase: Updating
  - name: wait_topology_again
    action: topology.wait_ready
  - name: wait_mc_resource_version_change
    action: k8s.resource.version.wait_change
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: wait_monitoring_console_again
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: list_versioned_secrets
    action: secret.versioned.list
    with:
      version: 2
  - name: verify_secret_objects
    action: secret.verify.objects
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_secret_pods
    action: secret.verify.pods
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_server_conf
    action: secret.verify.server_conf
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_inputs_conf
    action: secret.verify.inputs_conf
    with:
      data_path: ${old_secret_data_path}
      match: false
  - name: verify_api
    action: secret.verify.api
    with:
      data_path: ${old_secret_data_path}
      match: false
---
apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_secret_c3_update
  description: Secret update on clustered deployment (source test/secret/manager_secret_c3_test.go)
  component: secret
  tags: [operator, secret, c3, smoke]
variants:
  - name: operator_secret_manager_c3_update
    tags: [managersecret]
  - name: operator_secret_master_c3_update
    tags: [mastersecret]
    step_overrides:
      - name: deploy
        with:
          cluster_manager_kind: master
          license_master_ref: lm
          license_manager_ref: null
      - name: deploy_license_manager
        action: splunk.license_master.deploy
      - name: wait_license_manager
        action: splunk.license_master.wait_ready
      - name: deploy_monitoring_console
        with:
          license_master_ref: lm
          license_manager_ref: null
      - name: assert_cluster_manager_updating
        with:
          kind: ClusterMaster
          apiVersion: enterprise.splunk.com/v3
      - name: wait_license_manager_again
        action: splunk.license_master.wait_ready
requires: [license]
steps:
  - name: deploy
    action: topology.deploy
    with:
      kind: c3
      indexer_replicas: 3
      shc_replicas: 3
      with_shc: true
      license_manager_ref: lm
      monitoring_console_ref: mc
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_manager
    action: splunk.license_manager.deploy
    with:
      name: lm
  - name: wait_license_manager
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_ready
    action: topology.wait_ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: mc
      license_manager_ref: lm
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: capture_mc_resource_version
    action: k8s.resource.version.capture
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: assert_rf_sf_before
    action: assert.cluster.rf_sf
  - name: capture_secret
    action: secret.capture
  - name: generate_secret
    action: secret.generate
  - name: update_secret
    action: secret.update
  - name: assert_cluster_manager_updating
    action: assert.splunk.phase
    with:
      kind: ClusterManager
      name: ${cluster_manager_name}
      apiVersion: enterprise.splunk.com/v4
      phase: Updating
  - name: wait_license_manager_again
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_again
    action: topology.wait_ready
  - name: wait_mc_resource_version_change
    action: k8s.resource.version.wait_change
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: wait_monitoring_console_again
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: assert_rf_sf_after
    action: assert.cluster.rf_sf
  - name: list_versioned_secrets
    action: secret.versioned.list
    with:
      version: 2
  - name: verify_secret_objects
    action: secret.verify.objects
    with:
      match: true
  - name: verify_secret_pods
    action: secret.verify.pods
    with:
      match: true
  - name: verify_server_conf
    action: secret.verify.server_conf
    with:
      match: true
  - name: verify_inputs_conf
    action: secret.verify.inputs_conf
    with:
      match: true
  - name: verify_api
    action: secret.verify.api
    with:
      match: true
---
apiVersion: e2e.splunk.com/v1
kind: Test
metadata:
  name: operator_secret_m4_update
  description: Secret update on multisite deployment (source test/secret/manager_secret_m4_test.go)
  component: secret
  tags: [operator, secret, m4, integration]
variants:
  - name: operator_secret_manager_m4_update
    tags: [managersecret]
  - name: operator_secret_master_m4_update
    tags: [mastersecret]
    step_overrides:
      - name: deploy
        with:
          cluster_manager_kind: master
          license_master_ref: lm
          license_manager_ref: null
      - name: deploy_license_manager
        action: splunk.license_master.deploy
      - name: wait_license_manager
        action: splunk.license_master.wait_ready
      - name: deploy_monitoring_console
        with:
          license_master_ref: lm
          license_manager_ref: null
      - name: assert_cluster_manager_updating
        with:
          kind: ClusterMaster
          apiVersion: enterprise.splunk.com/v3
      - name: wait_license_manager_again
        action: splunk.license_master.wait_ready
requires: [license]
steps:
  - name: deploy
    action: topology.deploy
    with:
      kind: m4
      indexer_replicas: 1
      shc_replicas: 3
      site_count: 3
      license_manager_ref: lm
      monitoring_console_ref: mc
  - name: ensure_license_configmap
    action: license.configmap.ensure
  - name: deploy_license_manager
    action: splunk.license_manager.deploy
    with:
      name: lm
  - name: wait_license_manager
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_ready
    action: topology.wait_ready
  - name: deploy_monitoring_console
    action: splunk.monitoring_console.deploy
    with:
      name: mc
      license_manager_ref: lm
  - name: wait_monitoring_console
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: capture_mc_resource_version
    action: k8s.resource.version.capture
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: assert_rf_sf_before
    action: assert.cluster.rf_sf
  - name: capture_secret
    action: secret.capture
  - name: generate_secret
    action: secret.generate
  - name: update_secret
    action: secret.update
  - name: assert_cluster_manager_updating
    action: assert.splunk.phase
    with:
      kind: ClusterManager
      name: ${cluster_manager_name}
      apiVersion: enterprise.splunk.com/v4
      phase: Updating
  - name: wait_license_manager_again
    action: splunk.license_manager.wait_ready
    with:
      name: lm
  - name: wait_topology_again
    action: topology.wait_ready
  - name: wait_mc_resource_version_change
    action: k8s.resource.version.wait_change
    with:
      kind: MonitoringConsole
      name: mc
      apiVersion: enterprise.splunk.com/v4
      var: mc_resource_version
  - name: wait_monitoring_console_again
    action: splunk.monitoring_console.wait_ready
    with:
      name: mc
  - name: assert_rf_sf_after
    action: assert.cluster.rf_sf
  - name: list_versioned_secrets
    action: secret.versioned.list
    with:
      version: 2
  - name: verify_secret_objects
    action: secret.verify.objects
    with:
      match: true
  - name: verify_secret_pods
    action: secret.verify.pods
    with:
      match: true
  - name: verify_server_conf
    action: secret.verify.server_conf
    with:
      match: true
  - name: verify_inputs_conf
    action: secret.verify.inputs_conf
    with:
      match: true
  - name: verify_api
    action: secret.verify.api
    with:
      match: true
