name: 'Collect Test Artifacts'
description: 'Collect and upload pod logs and test artifacts'

inputs:
  artifact-name:
    description: 'Name for the artifact'
    required: true
  log-path:
    description: 'Path to collect logs from'
    required: false
    default: './test'
  additional-paths:
    description: 'Additional paths to collect (newline separated)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Collect Test Logs
      if: always()
      shell: bash
      run: |
        mkdir -p /tmp/pod_logs
        find ${{ inputs.log-path }} -name "*.log" -exec cp {} /tmp/pod_logs \; 2>/dev/null || true

        # Collect additional paths if specified
        if [ -n "${{ inputs.additional-paths }}" ]; then
          while IFS= read -r path; do
            [ -n "$path" ] && cp -r "$path" /tmp/pod_logs/ 2>/dev/null || true
          done <<< "${{ inputs.additional-paths }}"
        fi

    - name: Archive Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/pod_logs/**
        retention-days: 7
