apiVersion: apps.splunk.com/v1alpha1
kind: AppSource
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: appsource-sample
spec:
  # TODO(user): Add fields here
