apiVersion: enterprise.splunk.com/v4
kind: SplunkApp
metadata:
  labels:
    app.kubernetes.io/name: splunkapp
    app.kubernetes.io/instance: splunkapp-sample
    app.kubernetes.io/part-of: splunk-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: splunk-operator
  name: splunkapp-sample
spec:
  # TODO(user): Add fields here
