# Sample PostgresCluster using Postgres-dev ClusterClass with overriding defaults
# This sample demonstrates how to override default values from the ClusterClass "postgresql-dev" (see enterprise_v4_clusterclass_dev.yaml) in a PostgresCluster manifest.
# Overrides include changing storage, changing PostgreSQL version, and modifying resources.
apiVersion: enterprise.splunk.com/v4
kind: PostgresCluster
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-cluster-dev-overridden
spec:
  # Reference the ClusterClass to inherit defaults - this is required, immutable, and must match the name of an existing ClusterClass
  class: postgresql-dev
  instances: 2
  # Storage and PostgreSQL version are overridden from the ClusterClass defaults. Validation rules on the PostgresCluster resource will prevent removing these fields or setting them to lower values than the original overrides.
  storage: 1Gi
  postgresVersion: "15.10"
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"