apiVersion: enterprise.splunk.com/v4
kind: PostgresDatabase
metadata:
  name: test-postgresdatabase
  namespace: default
spec:
  clusterRef:
    name: postgres-cluster
  databases:
    - name: kvstore
      extensions:
        - pg_stat_statements
        - pgcrypto
      deletionPolicy: Retain
    - name: analytics
      extensions:
        - pg_trgm
      deletionPolicy: Delete
    - name: metrics
      # No extensions, default deletion policy (Delete)
