apiVersion: platform.splunk.com/v4
kind: TenantConfig
metadata:
  labels:
    app.kubernetes.io/name: splunk-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenantconfig-sample
spec:
  # TODO(user): Add fields here
