//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v4

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDeploymentContext) DeepCopyInto(out *AppDeploymentContext) {
	*out = *in
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
	if in.AppsSrcDeployStatus != nil {
		in, out := &in.AppsSrcDeployStatus, &out.AppsSrcDeployStatus
		*out = make(map[string]AppSrcDeployInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.BundlePushStatus = in.BundlePushStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDeploymentContext.
func (in *AppDeploymentContext) DeepCopy() *AppDeploymentContext {
	if in == nil {
		return nil
	}
	out := new(AppDeploymentContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDeploymentInfo) DeepCopyInto(out *AppDeploymentInfo) {
	*out = *in
	out.PhaseInfo = in.PhaseInfo
	if in.AuxPhaseInfo != nil {
		in, out := &in.AuxPhaseInfo, &out.AuxPhaseInfo
		*out = make([]PhaseInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDeploymentInfo.
func (in *AppDeploymentInfo) DeepCopy() *AppDeploymentInfo {
	if in == nil {
		return nil
	}
	out := new(AppDeploymentInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppFrameworkSpec) DeepCopyInto(out *AppFrameworkSpec) {
	*out = *in
	out.Defaults = in.Defaults
	if in.VolList != nil {
		in, out := &in.VolList, &out.VolList
		*out = make([]VolumeSpec, len(*in))
		copy(*out, *in)
	}
	if in.AppSources != nil {
		in, out := &in.AppSources, &out.AppSources
		*out = make([]AppSourceSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppFrameworkSpec.
func (in *AppFrameworkSpec) DeepCopy() *AppFrameworkSpec {
	if in == nil {
		return nil
	}
	out := new(AppFrameworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSourceDefaultSpec) DeepCopyInto(out *AppSourceDefaultSpec) {
	*out = *in
	out.PremiumAppsProps = in.PremiumAppsProps
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSourceDefaultSpec.
func (in *AppSourceDefaultSpec) DeepCopy() *AppSourceDefaultSpec {
	if in == nil {
		return nil
	}
	out := new(AppSourceDefaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSourceSpec) DeepCopyInto(out *AppSourceSpec) {
	*out = *in
	out.AppSourceDefaultSpec = in.AppSourceDefaultSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSourceSpec.
func (in *AppSourceSpec) DeepCopy() *AppSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AppSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSrcDeployInfo) DeepCopyInto(out *AppSrcDeployInfo) {
	*out = *in
	if in.AppDeploymentInfoList != nil {
		in, out := &in.AppDeploymentInfoList, &out.AppDeploymentInfoList
		*out = make([]AppDeploymentInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSrcDeployInfo.
func (in *AppSrcDeployInfo) DeepCopy() *AppSrcDeployInfo {
	if in == nil {
		return nil
	}
	out := new(AppSrcDeployInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfig) DeepCopyInto(out *BackupConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfig.
func (in *BackupConfig) DeepCopy() *BackupConfig {
	if in == nil {
		return nil
	}
	out := new(BackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(VolumeSnapshotBackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStore != nil {
		in, out := &in.ObjectStore, &out.ObjectStore
		*out = new(ObjectStoreBackupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapFrom) DeepCopyInto(out *BootstrapFrom) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(VolumeSnapshotSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(ObjectStorageSource)
		**out = **in
	}
	if in.RecoveryTarget != nil {
		in, out := &in.RecoveryTarget, &out.RecoveryTarget
		*out = new(RecoveryTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapFrom.
func (in *BootstrapFrom) DeepCopy() *BootstrapFrom {
	if in == nil {
		return nil
	}
	out := new(BootstrapFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundlePushInfo) DeepCopyInto(out *BundlePushInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundlePushInfo.
func (in *BundlePushInfo) DeepCopy() *BundlePushInfo {
	if in == nil {
		return nil
	}
	out := new(BundlePushInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundlePushTracker) DeepCopyInto(out *BundlePushTracker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundlePushTracker.
func (in *BundlePushTracker) DeepCopy() *BundlePushTracker {
	if in == nil {
		return nil
	}
	out := new(BundlePushTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBackupConfig) DeepCopyInto(out *CNPGBackupConfig) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(CNPGVolumeSnapshotConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BarmanObjectStore != nil {
		in, out := &in.BarmanObjectStore, &out.BarmanObjectStore
		*out = new(CNPGBarmanObjectStoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBackupConfig.
func (in *CNPGBackupConfig) DeepCopy() *CNPGBackupConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBarmanObjectStoreConfig) DeepCopyInto(out *CNPGBarmanObjectStoreConfig) {
	*out = *in
	if in.EndpointURL != nil {
		in, out := &in.EndpointURL, &out.EndpointURL
		*out = new(string)
		**out = **in
	}
	in.S3Credentials.DeepCopyInto(&out.S3Credentials)
	if in.WAL != nil {
		in, out := &in.WAL, &out.WAL
		*out = new(CNPGBarmanWALConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBarmanObjectStoreConfig.
func (in *CNPGBarmanObjectStoreConfig) DeepCopy() *CNPGBarmanObjectStoreConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGBarmanObjectStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBarmanS3Credentials) DeepCopyInto(out *CNPGBarmanS3Credentials) {
	*out = *in
	in.AccessKeyId.DeepCopyInto(&out.AccessKeyId)
	in.SecretAccessKey.DeepCopyInto(&out.SecretAccessKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBarmanS3Credentials.
func (in *CNPGBarmanS3Credentials) DeepCopy() *CNPGBarmanS3Credentials {
	if in == nil {
		return nil
	}
	out := new(CNPGBarmanS3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGBarmanWALConfig) DeepCopyInto(out *CNPGBarmanWALConfig) {
	*out = *in
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(string)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGBarmanWALConfig.
func (in *CNPGBarmanWALConfig) DeepCopy() *CNPGBarmanWALConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGBarmanWALConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGConfig) DeepCopyInto(out *CNPGConfig) {
	*out = *in
	if in.PrimaryUpdateMethod != nil {
		in, out := &in.PrimaryUpdateMethod, &out.PrimaryUpdateMethod
		*out = new(string)
		**out = **in
	}
	if in.ConnectionPooler != nil {
		in, out := &in.ConnectionPooler, &out.ConnectionPooler
		*out = new(ConnectionPoolerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(CNPGBackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGConfig.
func (in *CNPGConfig) DeepCopy() *CNPGConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNPGVolumeSnapshotConfig) DeepCopyInto(out *CNPGVolumeSnapshotConfig) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.WalClassName != nil {
		in, out := &in.WalClassName, &out.WalClassName
		*out = new(string)
		**out = **in
	}
	if in.SnapshotOwnerReference != nil {
		in, out := &in.SnapshotOwnerReference, &out.SnapshotOwnerReference
		*out = new(string)
		**out = **in
	}
	if in.Online != nil {
		in, out := &in.Online, &out.Online
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNPGVolumeSnapshotConfig.
func (in *CNPGVolumeSnapshotConfig) DeepCopy() *CNPGVolumeSnapshotConfig {
	if in == nil {
		return nil
	}
	out := new(CNPGVolumeSnapshotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheManagerSpec) DeepCopyInto(out *CacheManagerSpec) {
	*out = *in
	out.IndexAndCacheManagerCommonSpec = in.IndexAndCacheManagerCommonSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheManagerSpec.
func (in *CacheManagerSpec) DeepCopy() *CacheManagerSpec {
	if in == nil {
		return nil
	}
	out := new(CacheManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertSpec) DeepCopyInto(out *CertSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertSpec.
func (in *CertSpec) DeepCopy() *CertSpec {
	if in == nil {
		return nil
	}
	out := new(CertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManager) DeepCopyInto(out *ClusterManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManager.
func (in *ClusterManager) DeepCopy() *ClusterManager {
	if in == nil {
		return nil
	}
	out := new(ClusterManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerList) DeepCopyInto(out *ClusterManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerList.
func (in *ClusterManagerList) DeepCopy() *ClusterManagerList {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerSpec) DeepCopyInto(out *ClusterManagerSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	in.SmartStore.DeepCopyInto(&out.SmartStore)
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerSpec.
func (in *ClusterManagerSpec) DeepCopy() *ClusterManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterManagerStatus) DeepCopyInto(out *ClusterManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.SmartStore.DeepCopyInto(&out.SmartStore)
	out.BundlePushTracker = in.BundlePushTracker
	if in.ResourceRevMap != nil {
		in, out := &in.ResourceRevMap, &out.ResourceRevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.AppContext.DeepCopyInto(&out.AppContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterManagerStatus.
func (in *ClusterManagerStatus) DeepCopy() *ClusterManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonSplunkSpec) DeepCopyInto(out *CommonSplunkSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	out.EtcVolumeStorageConfig = in.EtcVolumeStorageConfig
	out.VarVolumeStorageConfig = in.VarVolumeStorageConfig
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.LicenseMasterRef = in.LicenseMasterRef
	out.LicenseManagerRef = in.LicenseManagerRef
	out.ClusterMasterRef = in.ClusterMasterRef
	out.ClusterManagerRef = in.ClusterManagerRef
	out.MonitoringConsoleRef = in.MonitoringConsoleRef
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(Probe)
		**out = **in
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(Probe)
		**out = **in
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(Probe)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Certs != nil {
		in, out := &in.Certs, &out.Certs
		*out = make([]CertSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonSplunkSpec.
func (in *CommonSplunkSpec) DeepCopy() *CommonSplunkSpec {
	if in == nil {
		return nil
	}
	out := new(CommonSplunkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolerConfig) DeepCopyInto(out *ConnectionPoolerConfig) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(ConnectionPoolerMode)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolerConfig.
func (in *ConnectionPoolerConfig) DeepCopy() *ConnectionPoolerConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolerEnableConfig) DeepCopyInto(out *ConnectionPoolerEnableConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ReadWrite != nil {
		in, out := &in.ReadWrite, &out.ReadWrite
		*out = new(bool)
		**out = **in
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolerEnableConfig.
func (in *ConnectionPoolerEnableConfig) DeepCopy() *ConnectionPoolerEnableConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolerEnableConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolerStatus) DeepCopyInto(out *ConnectionPoolerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolerStatus.
func (in *ConnectionPoolerStatus) DeepCopy() *ConnectionPoolerStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseDefinition) DeepCopyInto(out *DatabaseDefinition) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PasswordConfig != nil {
		in, out := &in.PasswordConfig, &out.PasswordConfig
		*out = new(PasswordConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseDefinition.
func (in *DatabaseDefinition) DeepCopy() *DatabaseDefinition {
	if in == nil {
		return nil
	}
	out := new(DatabaseDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseInfo) DeepCopyInto(out *DatabaseInfo) {
	*out = *in
	if in.DatabaseRef != nil {
		in, out := &in.DatabaseRef, &out.DatabaseRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.AdminUserSecretRef != nil {
		in, out := &in.AdminUserSecretRef, &out.AdminUserSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RWUserSecretRef != nil {
		in, out := &in.RWUserSecretRef, &out.RWUserSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]DatabaseRoleInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseInfo.
func (in *DatabaseInfo) DeepCopy() *DatabaseInfo {
	if in == nil {
		return nil
	}
	out := new(DatabaseInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleInfo) DeepCopyInto(out *DatabaseRoleInfo) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleInfo.
func (in *DatabaseRoleInfo) DeepCopy() *DatabaseRoleInfo {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsDefaults) DeepCopyInto(out *EsDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsDefaults.
func (in *EsDefaults) DeepCopy() *EsDefaults {
	if in == nil {
		return nil
	}
	out := new(EsDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexAndCacheManagerCommonSpec) DeepCopyInto(out *IndexAndCacheManagerCommonSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexAndCacheManagerCommonSpec.
func (in *IndexAndCacheManagerCommonSpec) DeepCopy() *IndexAndCacheManagerCommonSpec {
	if in == nil {
		return nil
	}
	out := new(IndexAndCacheManagerCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexAndGlobalCommonSpec) DeepCopyInto(out *IndexAndGlobalCommonSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexAndGlobalCommonSpec.
func (in *IndexAndGlobalCommonSpec) DeepCopy() *IndexAndGlobalCommonSpec {
	if in == nil {
		return nil
	}
	out := new(IndexAndGlobalCommonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexConfDefaultsSpec) DeepCopyInto(out *IndexConfDefaultsSpec) {
	*out = *in
	out.IndexAndGlobalCommonSpec = in.IndexAndGlobalCommonSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexConfDefaultsSpec.
func (in *IndexConfDefaultsSpec) DeepCopy() *IndexConfDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(IndexConfDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexSpec) DeepCopyInto(out *IndexSpec) {
	*out = *in
	out.IndexAndCacheManagerCommonSpec = in.IndexAndCacheManagerCommonSpec
	out.IndexAndGlobalCommonSpec = in.IndexAndGlobalCommonSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexSpec.
func (in *IndexSpec) DeepCopy() *IndexSpec {
	if in == nil {
		return nil
	}
	out := new(IndexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerCluster) DeepCopyInto(out *IndexerCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerCluster.
func (in *IndexerCluster) DeepCopy() *IndexerCluster {
	if in == nil {
		return nil
	}
	out := new(IndexerCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IndexerCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerClusterList) DeepCopyInto(out *IndexerClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IndexerCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerClusterList.
func (in *IndexerClusterList) DeepCopy() *IndexerClusterList {
	if in == nil {
		return nil
	}
	out := new(IndexerClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IndexerClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerClusterMemberStatus) DeepCopyInto(out *IndexerClusterMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerClusterMemberStatus.
func (in *IndexerClusterMemberStatus) DeepCopy() *IndexerClusterMemberStatus {
	if in == nil {
		return nil
	}
	out := new(IndexerClusterMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerClusterSpec) DeepCopyInto(out *IndexerClusterSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	if in.QueueRef != nil {
		in, out := &in.QueueRef, &out.QueueRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ObjectStorageRef != nil {
		in, out := &in.ObjectStorageRef, &out.ObjectStorageRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerClusterSpec.
func (in *IndexerClusterSpec) DeepCopy() *IndexerClusterSpec {
	if in == nil {
		return nil
	}
	out := new(IndexerClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexerClusterStatus) DeepCopyInto(out *IndexerClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IndexerSecretChanged != nil {
		in, out := &in.IndexerSecretChanged, &out.IndexerSecretChanged
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	if in.IdxcPasswordChangedSecrets != nil {
		in, out := &in.IdxcPasswordChangedSecrets, &out.IdxcPasswordChangedSecrets
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]IndexerClusterMemberStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexerClusterStatus.
func (in *IndexerClusterStatus) DeepCopy() *IndexerClusterStatus {
	if in == nil {
		return nil
	}
	out := new(IndexerClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestorCluster) DeepCopyInto(out *IngestorCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestorCluster.
func (in *IngestorCluster) DeepCopy() *IngestorCluster {
	if in == nil {
		return nil
	}
	out := new(IngestorCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestorClusterList) DeepCopyInto(out *IngestorClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IngestorCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestorClusterList.
func (in *IngestorClusterList) DeepCopy() *IngestorClusterList {
	if in == nil {
		return nil
	}
	out := new(IngestorClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestorClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestorClusterSpec) DeepCopyInto(out *IngestorClusterSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
	out.QueueRef = in.QueueRef
	out.ObjectStorageRef = in.ObjectStorageRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestorClusterSpec.
func (in *IngestorClusterSpec) DeepCopy() *IngestorClusterSpec {
	if in == nil {
		return nil
	}
	out := new(IngestorClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestorClusterStatus) DeepCopyInto(out *IngestorClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceRevMap != nil {
		in, out := &in.ResourceRevMap, &out.ResourceRevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.AppContext.DeepCopyInto(&out.AppContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestorClusterStatus.
func (in *IngestorClusterStatus) DeepCopy() *IngestorClusterStatus {
	if in == nil {
		return nil
	}
	out := new(IngestorClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseManager) DeepCopyInto(out *LicenseManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseManager.
func (in *LicenseManager) DeepCopy() *LicenseManager {
	if in == nil {
		return nil
	}
	out := new(LicenseManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LicenseManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseManagerList) DeepCopyInto(out *LicenseManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LicenseManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseManagerList.
func (in *LicenseManagerList) DeepCopy() *LicenseManagerList {
	if in == nil {
		return nil
	}
	out := new(LicenseManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LicenseManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseManagerSpec) DeepCopyInto(out *LicenseManagerSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseManagerSpec.
func (in *LicenseManagerSpec) DeepCopy() *LicenseManagerSpec {
	if in == nil {
		return nil
	}
	out := new(LicenseManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LicenseManagerStatus) DeepCopyInto(out *LicenseManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AppContext.DeepCopyInto(&out.AppContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LicenseManagerStatus.
func (in *LicenseManagerStatus) DeepCopy() *LicenseManagerStatus {
	if in == nil {
		return nil
	}
	out := new(LicenseManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRolesStatus) DeepCopyInto(out *ManagedRolesStatus) {
	*out = *in
	if in.Reconciled != nil {
		in, out := &in.Reconciled, &out.Reconciled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Failed != nil {
		in, out := &in.Failed, &out.Failed
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RoleOwners != nil {
		in, out := &in.RoleOwners, &out.RoleOwners
		*out = make(map[string]RoleOwnerReference, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]RoleConflict, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRolesStatus.
func (in *ManagedRolesStatus) DeepCopy() *ManagedRolesStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedRolesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsClassConfig) DeepCopyInto(out *MetricsClassConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsClassConfig.
func (in *MetricsClassConfig) DeepCopy() *MetricsClassConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConsole) DeepCopyInto(out *MonitoringConsole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConsole.
func (in *MonitoringConsole) DeepCopy() *MonitoringConsole {
	if in == nil {
		return nil
	}
	out := new(MonitoringConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringConsole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConsoleList) DeepCopyInto(out *MonitoringConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringConsole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConsoleList.
func (in *MonitoringConsoleList) DeepCopy() *MonitoringConsoleList {
	if in == nil {
		return nil
	}
	out := new(MonitoringConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConsoleSpec) DeepCopyInto(out *MonitoringConsoleSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConsoleSpec.
func (in *MonitoringConsoleSpec) DeepCopy() *MonitoringConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConsoleStatus) DeepCopyInto(out *MonitoringConsoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.BundlePushTracker = in.BundlePushTracker
	if in.ResourceRevMap != nil {
		in, out := &in.ResourceRevMap, &out.ResourceRevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.AppContext.DeepCopyInto(&out.AppContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConsoleStatus.
func (in *MonitoringConsoleStatus) DeepCopy() *MonitoringConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorage) DeepCopyInto(out *ObjectStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorage.
func (in *ObjectStorage) DeepCopy() *ObjectStorage {
	if in == nil {
		return nil
	}
	out := new(ObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageList) DeepCopyInto(out *ObjectStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageList.
func (in *ObjectStorageList) DeepCopy() *ObjectStorageList {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ObjectStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSource) DeepCopyInto(out *ObjectStorageSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSource.
func (in *ObjectStorageSource) DeepCopy() *ObjectStorageSource {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageSpec) DeepCopyInto(out *ObjectStorageSpec) {
	*out = *in
	out.S3 = in.S3
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageSpec.
func (in *ObjectStorageSpec) DeepCopy() *ObjectStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStorageStatus) DeepCopyInto(out *ObjectStorageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceRevMap != nil {
		in, out := &in.ResourceRevMap, &out.ResourceRevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStorageStatus.
func (in *ObjectStorageStatus) DeepCopy() *ObjectStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreBackupStatus) DeepCopyInto(out *ObjectStoreBackupStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreBackupStatus.
func (in *ObjectStoreBackupStatus) DeepCopy() *ObjectStoreBackupStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordConfig) DeepCopyInto(out *PasswordConfig) {
	*out = *in
	out.ExternalAdminSecretRef = in.ExternalAdminSecretRef
	out.ExternalRWSecretRef = in.ExternalRWSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordConfig.
func (in *PasswordConfig) DeepCopy() *PasswordConfig {
	if in == nil {
		return nil
	}
	out := new(PasswordConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseInfo) DeepCopyInto(out *PhaseInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseInfo.
func (in *PhaseInfo) DeepCopy() *PhaseInfo {
	if in == nil {
		return nil
	}
	out := new(PhaseInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresCluster) DeepCopyInto(out *PostgresCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresCluster.
func (in *PostgresCluster) DeepCopy() *PostgresCluster {
	if in == nil {
		return nil
	}
	out := new(PostgresCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClass) DeepCopyInto(out *PostgresClusterClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClass.
func (in *PostgresClusterClass) DeepCopy() *PostgresClusterClass {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassConfig) DeepCopyInto(out *PostgresClusterClassConfig) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.PostgresVersion != nil {
		in, out := &in.PostgresVersion, &out.PostgresVersion
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQLConfig != nil {
		in, out := &in.PostgreSQLConfig, &out.PostgreSQLConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PgHBA != nil {
		in, out := &in.PgHBA, &out.PgHBA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionPooler != nil {
		in, out := &in.ConnectionPooler, &out.ConnectionPooler
		*out = new(ConnectionPoolerEnableConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(PostgresMonitoringClassConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassConfig.
func (in *PostgresClusterClassConfig) DeepCopy() *PostgresClusterClassConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassList) DeepCopyInto(out *PostgresClusterClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresClusterClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassList.
func (in *PostgresClusterClassList) DeepCopy() *PostgresClusterClassList {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassSpec) DeepCopyInto(out *PostgresClusterClassSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(PostgresClusterClassConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CNPG != nil {
		in, out := &in.CNPG, &out.CNPG
		*out = new(CNPGConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassSpec.
func (in *PostgresClusterClassSpec) DeepCopy() *PostgresClusterClassSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterClassStatus) DeepCopyInto(out *PostgresClusterClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterClassStatus.
func (in *PostgresClusterClassStatus) DeepCopy() *PostgresClusterClassStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterList) DeepCopyInto(out *PostgresClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterList.
func (in *PostgresClusterList) DeepCopy() *PostgresClusterList {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterMonitoring) DeepCopyInto(out *PostgresClusterMonitoring) {
	*out = *in
	if in.PostgreSQLMetrics != nil {
		in, out := &in.PostgreSQLMetrics, &out.PostgreSQLMetrics
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionPoolerMetrics != nil {
		in, out := &in.ConnectionPoolerMetrics, &out.ConnectionPoolerMetrics
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterMonitoring.
func (in *PostgresClusterMonitoring) DeepCopy() *PostgresClusterMonitoring {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterResources) DeepCopyInto(out *PostgresClusterResources) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.SuperUserSecretRef != nil {
		in, out := &in.SuperUserSecretRef, &out.SuperUserSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterResources.
func (in *PostgresClusterResources) DeepCopy() *PostgresClusterResources {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterSpec) DeepCopyInto(out *PostgresClusterSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.PostgresVersion != nil {
		in, out := &in.PostgresVersion, &out.PostgresVersion
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQLConfig != nil {
		in, out := &in.PostgreSQLConfig, &out.PostgreSQLConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PgHBA != nil {
		in, out := &in.PgHBA, &out.PgHBA
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConnectionPooler != nil {
		in, out := &in.ConnectionPooler, &out.ConnectionPooler
		*out = new(ConnectionPoolerEnableConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterDeletionPolicy != nil {
		in, out := &in.ClusterDeletionPolicy, &out.ClusterDeletionPolicy
		*out = new(string)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(PostgresClusterMonitoring)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.BootstrapFrom != nil {
		in, out := &in.BootstrapFrom, &out.BootstrapFrom
		*out = new(BootstrapFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordConfig != nil {
		in, out := &in.PasswordConfig, &out.PasswordConfig
		*out = new(SuperuserPasswordConfig)
		**out = **in
	}
	if in.PostgresMajorUpgradeConfig != nil {
		in, out := &in.PostgresMajorUpgradeConfig, &out.PostgresMajorUpgradeConfig
		*out = new(PostgresMajorUpgradeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterSpec.
func (in *PostgresClusterSpec) DeepCopy() *PostgresClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresClusterStatus) DeepCopyInto(out *PostgresClusterStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.ProvisionerRef != nil {
		in, out := &in.ProvisionerRef, &out.ProvisionerRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ConnectionPoolerStatus != nil {
		in, out := &in.ConnectionPoolerStatus, &out.ConnectionPoolerStatus
		*out = new(ConnectionPoolerStatus)
		**out = **in
	}
	if in.ManagedRolesStatus != nil {
		in, out := &in.ManagedRolesStatus, &out.ManagedRolesStatus
		*out = new(ManagedRolesStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(PostgresClusterResources)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.ReadyInstances != nil {
		in, out := &in.ReadyInstances, &out.ReadyInstances
		*out = new(int32)
		**out = **in
	}
	if in.CurrentPrimary != nil {
		in, out := &in.CurrentPrimary, &out.CurrentPrimary
		*out = new(string)
		**out = **in
	}
	if in.PostgresMajorUpgradeStatus != nil {
		in, out := &in.PostgresMajorUpgradeStatus, &out.PostgresMajorUpgradeStatus
		*out = make([]PostgresMajorUpgradeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresClusterStatus.
func (in *PostgresClusterStatus) DeepCopy() *PostgresClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabase) DeepCopyInto(out *PostgresDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabase.
func (in *PostgresDatabase) DeepCopy() *PostgresDatabase {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseList) DeepCopyInto(out *PostgresDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostgresDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseList.
func (in *PostgresDatabaseList) DeepCopy() *PostgresDatabaseList {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostgresDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseSpec) DeepCopyInto(out *PostgresDatabaseSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseSpec.
func (in *PostgresDatabaseSpec) DeepCopy() *PostgresDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresDatabaseStatus) DeepCopyInto(out *PostgresDatabaseStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresDatabaseStatus.
func (in *PostgresDatabaseStatus) DeepCopy() *PostgresDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMajorUpgradeConfig) DeepCopyInto(out *PostgresMajorUpgradeConfig) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = new(bool)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMajorUpgradeConfig.
func (in *PostgresMajorUpgradeConfig) DeepCopy() *PostgresMajorUpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresMajorUpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMajorUpgradeStatus) DeepCopyInto(out *PostgresMajorUpgradeStatus) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.SourcePgVersion != nil {
		in, out := &in.SourcePgVersion, &out.SourcePgVersion
		*out = new(string)
		**out = **in
	}
	if in.TargetPgVersion != nil {
		in, out := &in.TargetPgVersion, &out.TargetPgVersion
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackupStatus != nil {
		in, out := &in.BackupStatus, &out.BackupStatus
		*out = new(BackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupNames != nil {
		in, out := &in.BackupNames, &out.BackupNames
		*out = new(UpgradeBackupNames)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMajorUpgradeStatus.
func (in *PostgresMajorUpgradeStatus) DeepCopy() *PostgresMajorUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(PostgresMajorUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresMonitoringClassConfig) DeepCopyInto(out *PostgresMonitoringClassConfig) {
	*out = *in
	if in.PostgreSQLMetrics != nil {
		in, out := &in.PostgreSQLMetrics, &out.PostgreSQLMetrics
		*out = new(MetricsClassConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConnectionPoolerMetrics != nil {
		in, out := &in.ConnectionPoolerMetrics, &out.ConnectionPoolerMetrics
		*out = new(MetricsClassConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresMonitoringClassConfig.
func (in *PostgresMonitoringClassConfig) DeepCopy() *PostgresMonitoringClassConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresMonitoringClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PremiumAppsProps) DeepCopyInto(out *PremiumAppsProps) {
	*out = *in
	out.EsDefaults = in.EsDefaults
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PremiumAppsProps.
func (in *PremiumAppsProps) DeepCopy() *PremiumAppsProps {
	if in == nil {
		return nil
	}
	out := new(PremiumAppsProps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probe) DeepCopyInto(out *Probe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probe.
func (in *Probe) DeepCopy() *Probe {
	if in == nil {
		return nil
	}
	out := new(Probe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Queue) DeepCopyInto(out *Queue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Queue.
func (in *Queue) DeepCopy() *Queue {
	if in == nil {
		return nil
	}
	out := new(Queue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueList) DeepCopyInto(out *QueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Queue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueList.
func (in *QueueList) DeepCopy() *QueueList {
	if in == nil {
		return nil
	}
	out := new(QueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
	in.SQS.DeepCopyInto(&out.SQS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSpec.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueStatus) DeepCopyInto(out *QueueStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceRevMap != nil {
		in, out := &in.ResourceRevMap, &out.ResourceRevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatus.
func (in *QueueStatus) DeepCopy() *QueueStatus {
	if in == nil {
		return nil
	}
	out := new(QueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTarget) DeepCopyInto(out *RecoveryTarget) {
	*out = *in
	if in.Exclusive != nil {
		in, out := &in.Exclusive, &out.Exclusive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTarget.
func (in *RecoveryTarget) DeepCopy() *RecoveryTarget {
	if in == nil {
		return nil
	}
	out := new(RecoveryTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoveryTargetStatus) DeepCopyInto(out *RecoveryTargetStatus) {
	*out = *in
	if in.Exclusive != nil {
		in, out := &in.Exclusive, &out.Exclusive
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoveryTargetStatus.
func (in *RecoveryTargetStatus) DeepCopy() *RecoveryTargetStatus {
	if in == nil {
		return nil
	}
	out := new(RecoveryTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreCredentialSweepStatus) DeepCopyInto(out *RestoreCredentialSweepStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreCredentialSweepStatus.
func (in *RestoreCredentialSweepStatus) DeepCopy() *RestoreCredentialSweepStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreCredentialSweepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSourceStatus) DeepCopyInto(out *RestoreSourceStatus) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(string)
		**out = **in
	}
	if in.ObjectStorage != nil {
		in, out := &in.ObjectStorage, &out.ObjectStorage
		*out = new(string)
		**out = **in
	}
	if in.RequestedRecoveryTarget != nil {
		in, out := &in.RequestedRecoveryTarget, &out.RequestedRecoveryTarget
		*out = new(RecoveryTargetStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSourceStatus.
func (in *RestoreSourceStatus) DeepCopy() *RestoreSourceStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreStatus) DeepCopyInto(out *RestoreStatus) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	out.CredentialSweep = in.CredentialSweep
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreStatus.
func (in *RestoreStatus) DeepCopy() *RestoreStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleConflict) DeepCopyInto(out *RoleConflict) {
	*out = *in
	if in.ClaimedBy != nil {
		in, out := &in.ClaimedBy, &out.ClaimedBy
		*out = new(RoleOwnerReference)
		**out = **in
	}
	out.AttemptedBy = in.AttemptedBy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleConflict.
func (in *RoleConflict) DeepCopy() *RoleConflict {
	if in == nil {
		return nil
	}
	out := new(RoleConflict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleOwnerReference) DeepCopyInto(out *RoleOwnerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleOwnerReference.
func (in *RoleOwnerReference) DeepCopy() *RoleOwnerReference {
	if in == nil {
		return nil
	}
	out := new(RoleOwnerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Spec) DeepCopyInto(out *S3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Spec.
func (in *S3Spec) DeepCopy() *S3Spec {
	if in == nil {
		return nil
	}
	out := new(S3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSSpec) DeepCopyInto(out *SQSSpec) {
	*out = *in
	if in.VolList != nil {
		in, out := &in.VolList, &out.VolList
		*out = make([]SQSVolumeSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSSpec.
func (in *SQSSpec) DeepCopy() *SQSSpec {
	if in == nil {
		return nil
	}
	out := new(SQSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQSVolumeSpec) DeepCopyInto(out *SQSVolumeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQSVolumeSpec.
func (in *SQSVolumeSpec) DeepCopy() *SQSVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(SQSVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadCluster) DeepCopyInto(out *SearchHeadCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadCluster.
func (in *SearchHeadCluster) DeepCopy() *SearchHeadCluster {
	if in == nil {
		return nil
	}
	out := new(SearchHeadCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchHeadCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterImageUpgradeStatus) DeepCopyInto(out *SearchHeadClusterImageUpgradeStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.PhaseStartedAt != nil {
		in, out := &in.PhaseStartedAt, &out.PhaseStartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.InitializationIntentAt != nil {
		in, out := &in.InitializationIntentAt, &out.InitializationIntentAt
		*out = (*in).DeepCopy()
	}
	if in.InitializationLastAttemptAt != nil {
		in, out := &in.InitializationLastAttemptAt, &out.InitializationLastAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.InitializationSucceededAt != nil {
		in, out := &in.InitializationSucceededAt, &out.InitializationSucceededAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedOrdinals != nil {
		in, out := &in.CompletedOrdinals, &out.CompletedOrdinals
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.FinalizationIntentAt != nil {
		in, out := &in.FinalizationIntentAt, &out.FinalizationIntentAt
		*out = (*in).DeepCopy()
	}
	if in.FinalizationLastAttemptAt != nil {
		in, out := &in.FinalizationLastAttemptAt, &out.FinalizationLastAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.FinalizationSucceededAt != nil {
		in, out := &in.FinalizationSucceededAt, &out.FinalizationSucceededAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterImageUpgradeStatus.
func (in *SearchHeadClusterImageUpgradeStatus) DeepCopy() *SearchHeadClusterImageUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterImageUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterLifecycleOperationStatus) DeepCopyInto(out *SearchHeadClusterLifecycleOperationStatus) {
	*out = *in
	if in.TargetOrdinal != nil {
		in, out := &in.TargetOrdinal, &out.TargetOrdinal
		*out = new(int32)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.StageStartedAt != nil {
		in, out := &in.StageStartedAt, &out.StageStartedAt
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.CompletedOrdinals != nil {
		in, out := &in.CompletedOrdinals, &out.CompletedOrdinals
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.CaptainTransferRequestedAt != nil {
		in, out := &in.CaptainTransferRequestedAt, &out.CaptainTransferRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.ReplacementAuthorizedAt != nil {
		in, out := &in.ReplacementAuthorizedAt, &out.ReplacementAuthorizedAt
		*out = (*in).DeepCopy()
	}
	if in.MembershipRemovalRequestedAt != nil {
		in, out := &in.MembershipRemovalRequestedAt, &out.MembershipRemovalRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.MemberRejoinStartedAt != nil {
		in, out := &in.MemberRejoinStartedAt, &out.MemberRejoinStartedAt
		*out = (*in).DeepCopy()
	}
	if in.DetentionReleaseRequestedAt != nil {
		in, out := &in.DetentionReleaseRequestedAt, &out.DetentionReleaseRequestedAt
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulSHCObservation != nil {
		in, out := &in.LastSuccessfulSHCObservation, &out.LastSuccessfulSHCObservation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterLifecycleOperationStatus.
func (in *SearchHeadClusterLifecycleOperationStatus) DeepCopy() *SearchHeadClusterLifecycleOperationStatus {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterLifecycleOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterLifecyclePolicy) DeepCopyInto(out *SearchHeadClusterLifecyclePolicy) {
	*out = *in
	if in.SearchDrainTimeoutSeconds != nil {
		in, out := &in.SearchDrainTimeoutSeconds, &out.SearchDrainTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.CaptainTransferTimeoutSeconds != nil {
		in, out := &in.CaptainTransferTimeoutSeconds, &out.CaptainTransferTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
	if in.MemberRejoinTimeoutSeconds != nil {
		in, out := &in.MemberRejoinTimeoutSeconds, &out.MemberRejoinTimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterLifecyclePolicy.
func (in *SearchHeadClusterLifecyclePolicy) DeepCopy() *SearchHeadClusterLifecyclePolicy {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterLifecyclePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterList) DeepCopyInto(out *SearchHeadClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SearchHeadCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterList.
func (in *SearchHeadClusterList) DeepCopy() *SearchHeadClusterList {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SearchHeadClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterMemberStatus) DeepCopyInto(out *SearchHeadClusterMemberStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterMemberStatus.
func (in *SearchHeadClusterMemberStatus) DeepCopy() *SearchHeadClusterMemberStatus {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterMemberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterSpec) DeepCopyInto(out *SearchHeadClusterSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
	in.DeployerResourceSpec.DeepCopyInto(&out.DeployerResourceSpec)
	if in.DeployerNodeAffinity != nil {
		in, out := &in.DeployerNodeAffinity, &out.DeployerNodeAffinity
		*out = new(corev1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.LifecyclePolicy != nil {
		in, out := &in.LifecyclePolicy, &out.LifecyclePolicy
		*out = new(SearchHeadClusterLifecyclePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterSpec.
func (in *SearchHeadClusterSpec) DeepCopy() *SearchHeadClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchHeadClusterStatus) DeepCopyInto(out *SearchHeadClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShcSecretChanged != nil {
		in, out := &in.ShcSecretChanged, &out.ShcSecretChanged
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	if in.AdminSecretChanged != nil {
		in, out := &in.AdminSecretChanged, &out.AdminSecretChanged
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	if in.AdminPasswordChangedSecrets != nil {
		in, out := &in.AdminPasswordChangedSecrets, &out.AdminPasswordChangedSecrets
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]SearchHeadClusterMemberStatus, len(*in))
		copy(*out, *in)
	}
	in.AppContext.DeepCopyInto(&out.AppContext)
	if in.LifecycleOperation != nil {
		in, out := &in.LifecycleOperation, &out.LifecycleOperation
		*out = new(SearchHeadClusterLifecycleOperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageUpgrade != nil {
		in, out := &in.ImageUpgrade, &out.ImageUpgrade
		*out = new(SearchHeadClusterImageUpgradeStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchHeadClusterStatus.
func (in *SearchHeadClusterStatus) DeepCopy() *SearchHeadClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SearchHeadClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmartStoreSpec) DeepCopyInto(out *SmartStoreSpec) {
	*out = *in
	if in.VolList != nil {
		in, out := &in.VolList, &out.VolList
		*out = make([]VolumeSpec, len(*in))
		copy(*out, *in)
	}
	if in.IndexList != nil {
		in, out := &in.IndexList, &out.IndexList
		*out = make([]IndexSpec, len(*in))
		copy(*out, *in)
	}
	out.Defaults = in.Defaults
	out.CacheManagerConf = in.CacheManagerConf
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmartStoreSpec.
func (in *SmartStoreSpec) DeepCopy() *SmartStoreSpec {
	if in == nil {
		return nil
	}
	out := new(SmartStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spec) DeepCopyInto(out *Spec) {
	*out = *in
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.ServiceTemplate.DeepCopyInto(&out.ServiceTemplate)
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spec.
func (in *Spec) DeepCopy() *Spec {
	if in == nil {
		return nil
	}
	out := new(Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Standalone) DeepCopyInto(out *Standalone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Standalone.
func (in *Standalone) DeepCopy() *Standalone {
	if in == nil {
		return nil
	}
	out := new(Standalone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Standalone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandaloneList) DeepCopyInto(out *StandaloneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Standalone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandaloneList.
func (in *StandaloneList) DeepCopy() *StandaloneList {
	if in == nil {
		return nil
	}
	out := new(StandaloneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StandaloneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandaloneSpec) DeepCopyInto(out *StandaloneSpec) {
	*out = *in
	in.CommonSplunkSpec.DeepCopyInto(&out.CommonSplunkSpec)
	in.SmartStore.DeepCopyInto(&out.SmartStore)
	in.AppFrameworkConfig.DeepCopyInto(&out.AppFrameworkConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandaloneSpec.
func (in *StandaloneSpec) DeepCopy() *StandaloneSpec {
	if in == nil {
		return nil
	}
	out := new(StandaloneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandaloneStatus) DeepCopyInto(out *StandaloneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.SmartStore.DeepCopyInto(&out.SmartStore)
	if in.ResourceRevMap != nil {
		in, out := &in.ResourceRevMap, &out.ResourceRevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.AppContext.DeepCopyInto(&out.AppContext)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandaloneStatus.
func (in *StandaloneStatus) DeepCopy() *StandaloneStatus {
	if in == nil {
		return nil
	}
	out := new(StandaloneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassSpec) DeepCopyInto(out *StorageClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassSpec.
func (in *StorageClassSpec) DeepCopy() *StorageClassSpec {
	if in == nil {
		return nil
	}
	out := new(StorageClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperuserPasswordConfig) DeepCopyInto(out *SuperuserPasswordConfig) {
	*out = *in
	out.SuperuserExternalSecretRef = in.SuperuserExternalSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperuserPasswordConfig.
func (in *SuperuserPasswordConfig) DeepCopy() *SuperuserPasswordConfig {
	if in == nil {
		return nil
	}
	out := new(SuperuserPasswordConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeBackupNames) DeepCopyInto(out *UpgradeBackupNames) {
	*out = *in
	if in.PreUpgrade != nil {
		in, out := &in.PreUpgrade, &out.PreUpgrade
		*out = new(string)
		**out = **in
	}
	if in.PostUpgrade != nil {
		in, out := &in.PostUpgrade, &out.PostUpgrade
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeBackupNames.
func (in *UpgradeBackupNames) DeepCopy() *UpgradeBackupNames {
	if in == nil {
		return nil
	}
	out := new(UpgradeBackupNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAndTypeSpec) DeepCopyInto(out *VolumeAndTypeSpec) {
	*out = *in
	out.VolumeSpec = in.VolumeSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAndTypeSpec.
func (in *VolumeAndTypeSpec) DeepCopy() *VolumeAndTypeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeAndTypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotBackupStatus) DeepCopyInto(out *VolumeSnapshotBackupStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.NextScheduleTime != nil {
		in, out := &in.NextScheduleTime, &out.NextScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotBackupStatus.
func (in *VolumeSnapshotBackupStatus) DeepCopy() *VolumeSnapshotBackupStatus {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotSource) DeepCopyInto(out *VolumeSnapshotSource) {
	*out = *in
	if in.WalStorage != nil {
		in, out := &in.WalStorage, &out.WalStorage
		*out = new(string)
		**out = **in
	}
	if in.WalArchive != nil {
		in, out := &in.WalArchive, &out.WalArchive
		*out = new(ObjectStorageSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotSource.
func (in *VolumeSnapshotSource) DeepCopy() *VolumeSnapshotSource {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSpec.
func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}
