apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tun-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: tun-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tun-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tun-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoExecute
        - operator: Exists
          effect: NoSchedule
      containers:
        - name: generic-device-plugin
          image: squat/generic-device-plugin:latest
          args:
            - --domain=github.com
            - --device
            - |
              name: tun
              groups:
                - count: 256
                  paths:
                    - path: /dev/net/tun
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev
              mountPath: /dev
              readOnly: true
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
