apiVersion: v1
kind: Service
metadata:
  labels:
{{- include "splunk-operator.labels" . | nindent 4 }}
  name: {{ include "splunk-operator.operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{ include "splunk-operator.namespace" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
{{- include "splunk-operator.labels" . | nindent 4 }}
