apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
