{{- if .Values.splunkOperator.clusterWideAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-clustermaster-viewer-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters/status
  verbs:
  - get
{{- end }}