{{- if .Values.splunkOperator.clusterWideAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "splunk-operator.operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
    - clustermanagers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - enterprise.splunk.com
  resources:
    - clustermanagers/finalizers
  verbs:
    - update
- apiGroups:
    - enterprise.splunk.com
  resources:
    - clustermanagers/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - enterprise.splunk.com
  resources:
  - indexerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - indexerclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - licensemasters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
    - licensemanagers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - enterprise.splunk.com
  resources:
    - licensemanagers/finalizers
  verbs:
    - update
- apiGroups:
    - enterprise.splunk.com
  resources:
    - licensemanagers/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - enterprise.splunk.com
  resources:
  - monitoringconsoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - searchheadclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - standalones/status
  verbs:
  - get
  - patch
  - update
{{- end }}