{{- if .Values.splunkOperator.clusterWideAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "splunk-operator.operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "splunk-operator.operator.fullname" . }}-controller-manager
  namespace: {{ include "splunk-operator.namespace" . }}
{{- end }}