apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-clustermaster-editor-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermasters/status
  verbs:
  - get
