apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "splunk-operator.operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "splunk-operator.operator.fullname" . }}-controller-manager
  namespace: {{ include "splunk-operator.namespace" . }}
