apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "splunk-operator.operator.fullname" . }}-monitoringconsole-viewer-role
rules:
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - monitoringconsoles/status
  verbs:
  - get
