---
{{- if not .Values.splunkOperator.clusterWideAccess }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "splunk-operator.operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - pods/exec
  - secrets
  - serviceaccounts
  - services
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermanagers
  - clustermasters
  - indexerclusters
  - kvservices
  - licensemanagers
  - licensemasters
  - monitoringconsoles
  - searchheadclusters
  - standalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermanagers/finalizers
  - clustermasters/finalizers
  - indexerclusters/finalizers
  - kvservices/finalizers
  - licensemanagers/finalizers
  - licensemasters/finalizers
  - monitoringconsoles/finalizers
  - searchheadclusters/finalizers
  - standalones/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.com
  resources:
  - clustermanagers/status
  - clustermasters/status
  - indexerclusters/status
  - kvservices/status
  - licensemanagers/status
  - licensemasters/status
  - monitoringconsoles/status
  - searchheadclusters/status
  - standalones/status
  verbs:
  - get
  - patch
  - update
{{- end }}