{{- if or .Values.conf.outputs .Values.conf.inputs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "splunk-universalforwarder.fullname" . }}-conf
  namespace: {{ include "splunk-universalforwarder.namespace" . }}
  labels:
    {{- include "splunk-universalforwarder.labels" . | nindent 4 }}
data:
  {{- if .Values.conf.outputs }}
  outputs.conf: |
    {{- .Values.conf.outputs | nindent 4 }}
  {{- end }}
  {{- if .Values.conf.inputs }}
  inputs.conf: |
    {{- .Values.conf.inputs | nindent 4 }}
  {{- end }}
{{- end }}
