# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunkaiplatform.fullname" . }}
  labels:
    {{- include "splunkaiplatform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "splunkaiplatform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
