apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
          value: splunk/splunk:10.0.0
        - name: SPLUNK_GENERAL_TERMS
          value: --accept-sgt-current-at-splunk-com
