# Entrypoint for helm automation
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./kuttl/tests/helm
parallel: 1
timeout: 7000
startKIND: false
artifactsDir: kuttl-artifacts
kindNodeCache: false
