apiVersion: enterprise.splunk.com/v3
kind: LicenseManager
metadata:
  name: lm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
---
apiVersion: enterprise.splunk.com/v3
kind: ClusterManager
metadata:
  name: cm-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  licenseManagerRef:
    name: lm-example
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: cluster
    appSources:
      - name: idxApps
        location: <apps-location>
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: aws
        path: <apps-path>
        endpoint: https://<apps-endpoint>
        secretRef: s3-secret
  smartstore:
    defaults:
        volumeName: volume_smartstore
    indexes:
      - name: main
        volumeName: volume_smartstore
    volumes:
        - name: volume_smartstore
        path: <smartstore-path>
        endpoint: https://<smartstore-endpoint>
        secretRef: s3-secret
---
apiVersion: enterprise.splunk.com/v3
kind: IndexerCluster
metadata:
  name: idxc-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  replicas: <n>
  clusterManagerRef:
    name: cm-example
  licenseManagerRef:
    name: lm-example
---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: sh-example
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: cm-example
  licenseManagerRef:
    name: lm-example
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: local
    appSources:
      - name: shApps
        location: <apps-location>
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: aws
        path: <apps-path>
        endpoint: https://<apps-endpoint>
        secretRef: s3-secret 
