apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  smartstore:
    defaults:
        volumeName: volume_smartstore
    indexes:
      - name: main
        remotePath: $_index_name
        volumeName: volume_smartstore
    volumes:
      - name: volume_smartstore
        path: <s3-path>
        endpoint: https://<s3-endpoint>
        secretRef: s3-secret
  appRepo:
    appsRepoPollIntervalSeconds: 600
    defaults:
      volumeName: volume_app_repo
      scope: local
    appSources:
      - name: s1Apps
        location: <apps-location>
    volumes:
      - name: volume_app_repo
        storageType: s3
        provider: aws
        path: <s3-path>
        endpoint: https://<s3-endpoint>
        secretRef: s3-secret
