apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-operator-controller-manager
  namespace: splunk-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: manager
          image: ${{ env.SPLUNK_OPERATOR_IMAGE_NAME }}:$GITHUB_SHA-distroless
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: RELATED_IMAGE_SPLUNK_ENTERPRISE
              value: splunk/splunk:9.4.0
        - name: debug-sidecar
          image: busybox:latest
          command: [ "/bin/bash", "-c", "tail -f /dev/null" ]
          volumeMounts:
            - name: app-staging
              mountPath: /opt/splunk/appframework/
      volumes:
        - name: app-staging
          persistentVolumeClaim:
            claimName: splunk-operator-app-download