name: Test Push to ECR
on:
  pull_request: {}
jobs:
  rc-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deep Fetch
        run: |
          git fetch --prune --unshallow

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@d4d12eaa0e1dd06d5bdc3d7af3bf4c8c93cb5359
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.dotenv.outputs.GO_VERSION }}

      - name: Install Operator SDK
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/${{ steps.dotenv.outputs.OPERATOR_SDK_VERSION }}
          sudo curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          sudo chmod +x operator-sdk_${OS}_${ARCH}
          sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

      # Build and push UBI image
      - name: Build and push UBI Image
        run: |
          make docker-buildx IMG=public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC1 BASE_IMAGE=registry.access.redhat.com/ubi8/ubi-minimal BASE_IMAGE_VERSION=latest

      # Build and push Distroless image
      - name: Build and push Distroless Image
        run: |
          make docker-buildx IMG=public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC1 BASE_IMAGE=gcr.io/distroless/static BASE_IMAGE_VERSION=latest

      - name: Tag and Push Default UBI RC Image
        run: |
          docker tag public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC1 public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC
          docker push public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC

      - name: Tag and Push Default Distroless RC Image
        run: |
          docker tag public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC1-distroless public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC-distroless
          docker push public.ecr.aws/t7s8z8m6/splunk/splunk-operator-rc:test-ecr-push-RC-distroless
